// <auto-generated />
using System;
using BicTechBack.src.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415201822_CarritoDetalleColor")]
    partial class CarritoDetalleColor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Carrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carritos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_carritos_usuario_id");

                    b.ToTable("carritos", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.CarritoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("CarritoId")
                        .HasColumnType("integer")
                        .HasColumnName("carrito_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("pk_carritos_detalles");

                    b.HasIndex("CarritoId")
                        .HasDatabaseName("ix_carritos_detalles_carrito_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_carritos_detalles_producto_id");

                    b.ToTable("carritos_detalles", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.CategoriaMarca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.HasKey("Id")
                        .HasName("pk_categorias_marcas");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_categorias_marcas_categoria_id");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_categorias_marcas_marca_id");

                    b.ToTable("categorias_marcas", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer")
                        .HasColumnName("pais_id");

                    b.HasKey("Id")
                        .HasName("pk_marcas");

                    b.HasIndex("PaisId")
                        .HasDatabaseName("ix_marcas_pais_id");

                    b.ToTable("marcas", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_paises");

                    b.ToTable("paises", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionEnvio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("direccion_envio");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedidos");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedidos_usuario_id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.PedidoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id")
                        .HasName("pk_pedidos_detalles");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedidos_detalles_pedido_id");

                    b.HasIndex("ProductoId")
                        .HasDatabaseName("ix_pedidos_detalles_producto_id");

                    b.ToTable("pedidos_detalles", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<int>("MarcaId")
                        .HasColumnType("integer")
                        .HasColumnName("marca_id");

                    b.Property<string>("MaterialFunda")
                        .HasColumnType("text")
                        .HasColumnName("material_funda");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("Stock")
                        .HasColumnType("integer")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("pk_productos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_productos_categoria_id");

                    b.HasIndex("MarcaId")
                        .HasDatabaseName("ix_productos_marca_id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Carrito", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Usuario", "Usuario")
                        .WithMany("Carritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carritos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.CarritoDetalle", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Carrito", "Carrito")
                        .WithMany("CarritosDetalles")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carritos_detalles_carritos_carrito_id");

                    b.HasOne("BicTechBack.src.Core.Entities.Producto", "Producto")
                        .WithMany("CarritosDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carritos_detalles_productos_producto_id");

                    b.Navigation("Carrito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.CategoriaMarca", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Categoria", "Categoria")
                        .WithMany("CategoriasMarcas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_marcas_categorias_categoria_id");

                    b.HasOne("BicTechBack.src.Core.Entities.Marca", "Marca")
                        .WithMany("CategoriasMarcas")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categorias_marcas_marcas_marca_id");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Marca", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Pais", "Pais")
                        .WithMany("Marcas")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_marcas_paises_pais_id");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Pedido", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Pedido", "Pedido")
                        .WithMany("PedidosDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_detalles_pedidos_pedido_id");

                    b.HasOne("BicTechBack.src.Core.Entities.Producto", "Producto")
                        .WithMany("PedidosDetalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_detalles_productos_producto_id");

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Producto", b =>
                {
                    b.HasOne("BicTechBack.src.Core.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_categorias_categoria_id");

                    b.HasOne("BicTechBack.src.Core.Entities.Marca", "Marca")
                        .WithMany("Productos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_productos_marcas_marca_id");

                    b.Navigation("Categoria");

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Carrito", b =>
                {
                    b.Navigation("CarritosDetalles");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Categoria", b =>
                {
                    b.Navigation("CategoriasMarcas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Marca", b =>
                {
                    b.Navigation("CategoriasMarcas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Pais", b =>
                {
                    b.Navigation("Marcas");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Pedido", b =>
                {
                    b.Navigation("PedidosDetalles");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Producto", b =>
                {
                    b.Navigation("CarritosDetalles");

                    b.Navigation("PedidosDetalles");
                });

            modelBuilder.Entity("BicTechBack.src.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
