CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;
CREATE TABLE "Categorias" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
);

CREATE TABLE "Paises" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    CONSTRAINT "PK_Paises" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "Rol" integer NOT NULL,
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Marcas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "PaisId" integer NOT NULL,
    CONSTRAINT "PK_Marcas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Marcas_Paises_PaisId" FOREIGN KEY ("PaisId") REFERENCES "Paises" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Carritos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "ActualizadoEn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Carritos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Carritos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Pedidos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "FechaPedido" timestamp with time zone NOT NULL,
    "Total" numeric(18,2) NOT NULL,
    "Estado" integer NOT NULL,
    "DireccionEnvio" text NOT NULL,
    CONSTRAINT "PK_Pedidos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Pedidos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CategoriasMarcas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CategoriaId" integer NOT NULL,
    "MarcaId" integer NOT NULL,
    CONSTRAINT "PK_CategoriasMarcas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CategoriasMarcas_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CategoriasMarcas_Marcas_MarcaId" FOREIGN KEY ("MarcaId") REFERENCES "Marcas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Productos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Precio" numeric(18,2) NOT NULL,
    "Descripcion" text NOT NULL,
    "CategoriaId" integer NOT NULL,
    "MarcaId" integer NOT NULL,
    "Stock" integer NOT NULL,
    "ImagenUrl" text NOT NULL,
    CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Productos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Productos_Marcas_MarcaId" FOREIGN KEY ("MarcaId") REFERENCES "Marcas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CarritosDetalles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CarritoId" integer NOT NULL,
    "ProductoId" integer NOT NULL,
    "Cantidad" integer NOT NULL,
    CONSTRAINT "PK_CarritosDetalles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CarritosDetalles_Carritos_CarritoId" FOREIGN KEY ("CarritoId") REFERENCES "Carritos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CarritosDetalles_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PedidosDetalles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PedidoId" integer NOT NULL,
    "ProductoId" integer NOT NULL,
    "Cantidad" integer NOT NULL,
    "Precio" numeric(18,2) NOT NULL,
    "Subtotal" numeric(18,2) NOT NULL,
    CONSTRAINT "PK_PedidosDetalles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PedidosDetalles_Pedidos_PedidoId" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PedidosDetalles_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Carritos_UsuarioId" ON "Carritos" ("UsuarioId");

CREATE INDEX "IX_CarritosDetalles_CarritoId" ON "CarritosDetalles" ("CarritoId");

CREATE INDEX "IX_CarritosDetalles_ProductoId" ON "CarritosDetalles" ("ProductoId");

CREATE INDEX "IX_CategoriasMarcas_CategoriaId" ON "CategoriasMarcas" ("CategoriaId");

CREATE INDEX "IX_CategoriasMarcas_MarcaId" ON "CategoriasMarcas" ("MarcaId");

CREATE INDEX "IX_Marcas_PaisId" ON "Marcas" ("PaisId");

CREATE INDEX "IX_Pedidos_UsuarioId" ON "Pedidos" ("UsuarioId");

CREATE INDEX "IX_PedidosDetalles_PedidoId" ON "PedidosDetalles" ("PedidoId");

CREATE INDEX "IX_PedidosDetalles_ProductoId" ON "PedidosDetalles" ("ProductoId");

CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");

CREATE INDEX "IX_Productos_MarcaId" ON "Productos" ("MarcaId");

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260407035954_InitialPostgreSql', '9.0.9');

ALTER TABLE "Carritos" DROP CONSTRAINT "FK_Carritos_Usuarios_UsuarioId";

ALTER TABLE "CarritosDetalles" DROP CONSTRAINT "FK_CarritosDetalles_Carritos_CarritoId";

ALTER TABLE "CarritosDetalles" DROP CONSTRAINT "FK_CarritosDetalles_Productos_ProductoId";

ALTER TABLE "CategoriasMarcas" DROP CONSTRAINT "FK_CategoriasMarcas_Categorias_CategoriaId";

ALTER TABLE "CategoriasMarcas" DROP CONSTRAINT "FK_CategoriasMarcas_Marcas_MarcaId";

ALTER TABLE "Marcas" DROP CONSTRAINT "FK_Marcas_Paises_PaisId";

ALTER TABLE "Pedidos" DROP CONSTRAINT "FK_Pedidos_Usuarios_UsuarioId";

ALTER TABLE "PedidosDetalles" DROP CONSTRAINT "FK_PedidosDetalles_Pedidos_PedidoId";

ALTER TABLE "PedidosDetalles" DROP CONSTRAINT "FK_PedidosDetalles_Productos_ProductoId";

ALTER TABLE "Productos" DROP CONSTRAINT "FK_Productos_Categorias_CategoriaId";

ALTER TABLE "Productos" DROP CONSTRAINT "FK_Productos_Marcas_MarcaId";

ALTER TABLE "Usuarios" DROP CONSTRAINT "PK_Usuarios";

ALTER TABLE "Productos" DROP CONSTRAINT "PK_Productos";

ALTER TABLE "Pedidos" DROP CONSTRAINT "PK_Pedidos";

ALTER TABLE "Paises" DROP CONSTRAINT "PK_Paises";

ALTER TABLE "Marcas" DROP CONSTRAINT "PK_Marcas";

ALTER TABLE "Categorias" DROP CONSTRAINT "PK_Categorias";

ALTER TABLE "Carritos" DROP CONSTRAINT "PK_Carritos";

ALTER TABLE "PedidosDetalles" DROP CONSTRAINT "PK_PedidosDetalles";

ALTER TABLE "CategoriasMarcas" DROP CONSTRAINT "PK_CategoriasMarcas";

ALTER TABLE "CarritosDetalles" DROP CONSTRAINT "PK_CarritosDetalles";

ALTER TABLE "Usuarios" RENAME TO usuarios;

ALTER TABLE "Productos" RENAME TO productos;

ALTER TABLE "Pedidos" RENAME TO pedidos;

ALTER TABLE "Paises" RENAME TO paises;

ALTER TABLE "Marcas" RENAME TO marcas;

ALTER TABLE "Categorias" RENAME TO categorias;

ALTER TABLE "Carritos" RENAME TO carritos;

ALTER TABLE "PedidosDetalles" RENAME TO pedidos_detalles;

ALTER TABLE "CategoriasMarcas" RENAME TO categorias_marcas;

ALTER TABLE "CarritosDetalles" RENAME TO carritos_detalles;

ALTER TABLE usuarios RENAME COLUMN "Rol" TO rol;

ALTER TABLE usuarios RENAME COLUMN "Password" TO password;

ALTER TABLE usuarios RENAME COLUMN "Nombre" TO nombre;

ALTER TABLE usuarios RENAME COLUMN "Email" TO email;

ALTER TABLE usuarios RENAME COLUMN "Id" TO id;

ALTER TABLE usuarios RENAME COLUMN "RefreshTokenExpiryTime" TO refresh_token_expiry_time;

ALTER TABLE usuarios RENAME COLUMN "RefreshToken" TO refresh_token;

ALTER TABLE productos RENAME COLUMN "Stock" TO stock;

ALTER TABLE productos RENAME COLUMN "Precio" TO precio;

ALTER TABLE productos RENAME COLUMN "Nombre" TO nombre;

ALTER TABLE productos RENAME COLUMN "Descripcion" TO descripcion;

ALTER TABLE productos RENAME COLUMN "Id" TO id;

ALTER TABLE productos RENAME COLUMN "MarcaId" TO marca_id;

ALTER TABLE productos RENAME COLUMN "ImagenUrl" TO imagen_url;

ALTER TABLE productos RENAME COLUMN "CategoriaId" TO categoria_id;

ALTER INDEX "IX_Productos_MarcaId" RENAME TO ix_productos_marca_id;

ALTER INDEX "IX_Productos_CategoriaId" RENAME TO ix_productos_categoria_id;

ALTER TABLE pedidos RENAME COLUMN "Total" TO total;

ALTER TABLE pedidos RENAME COLUMN "Estado" TO estado;

ALTER TABLE pedidos RENAME COLUMN "Id" TO id;

ALTER TABLE pedidos RENAME COLUMN "UsuarioId" TO usuario_id;

ALTER TABLE pedidos RENAME COLUMN "FechaPedido" TO fecha_pedido;

ALTER TABLE pedidos RENAME COLUMN "DireccionEnvio" TO direccion_envio;

ALTER INDEX "IX_Pedidos_UsuarioId" RENAME TO ix_pedidos_usuario_id;

ALTER TABLE paises RENAME COLUMN "Nombre" TO nombre;

ALTER TABLE paises RENAME COLUMN "Id" TO id;

ALTER TABLE marcas RENAME COLUMN "Nombre" TO nombre;

ALTER TABLE marcas RENAME COLUMN "Id" TO id;

ALTER TABLE marcas RENAME COLUMN "PaisId" TO pais_id;

ALTER INDEX "IX_Marcas_PaisId" RENAME TO ix_marcas_pais_id;

ALTER TABLE categorias RENAME COLUMN "Nombre" TO nombre;

ALTER TABLE categorias RENAME COLUMN "Id" TO id;

ALTER TABLE carritos RENAME COLUMN "Id" TO id;

ALTER TABLE carritos RENAME COLUMN "UsuarioId" TO usuario_id;

ALTER TABLE carritos RENAME COLUMN "ActualizadoEn" TO actualizado_en;

ALTER INDEX "IX_Carritos_UsuarioId" RENAME TO ix_carritos_usuario_id;

ALTER TABLE pedidos_detalles RENAME COLUMN "Subtotal" TO subtotal;

ALTER TABLE pedidos_detalles RENAME COLUMN "Precio" TO precio;

ALTER TABLE pedidos_detalles RENAME COLUMN "Cantidad" TO cantidad;

ALTER TABLE pedidos_detalles RENAME COLUMN "Id" TO id;

ALTER TABLE pedidos_detalles RENAME COLUMN "ProductoId" TO producto_id;

ALTER TABLE pedidos_detalles RENAME COLUMN "PedidoId" TO pedido_id;

ALTER INDEX "IX_PedidosDetalles_ProductoId" RENAME TO ix_pedidos_detalles_producto_id;

ALTER INDEX "IX_PedidosDetalles_PedidoId" RENAME TO ix_pedidos_detalles_pedido_id;

ALTER TABLE categorias_marcas RENAME COLUMN "Id" TO id;

ALTER TABLE categorias_marcas RENAME COLUMN "MarcaId" TO marca_id;

ALTER TABLE categorias_marcas RENAME COLUMN "CategoriaId" TO categoria_id;

ALTER INDEX "IX_CategoriasMarcas_MarcaId" RENAME TO ix_categorias_marcas_marca_id;

ALTER INDEX "IX_CategoriasMarcas_CategoriaId" RENAME TO ix_categorias_marcas_categoria_id;

ALTER TABLE carritos_detalles RENAME COLUMN "Cantidad" TO cantidad;

ALTER TABLE carritos_detalles RENAME COLUMN "Id" TO id;

ALTER TABLE carritos_detalles RENAME COLUMN "ProductoId" TO producto_id;

ALTER TABLE carritos_detalles RENAME COLUMN "CarritoId" TO carrito_id;

ALTER INDEX "IX_CarritosDetalles_ProductoId" RENAME TO ix_carritos_detalles_producto_id;

ALTER INDEX "IX_CarritosDetalles_CarritoId" RENAME TO ix_carritos_detalles_carrito_id;

ALTER TABLE usuarios ADD CONSTRAINT pk_usuarios PRIMARY KEY (id);

ALTER TABLE productos ADD CONSTRAINT pk_productos PRIMARY KEY (id);

ALTER TABLE pedidos ADD CONSTRAINT pk_pedidos PRIMARY KEY (id);

ALTER TABLE paises ADD CONSTRAINT pk_paises PRIMARY KEY (id);

ALTER TABLE marcas ADD CONSTRAINT pk_marcas PRIMARY KEY (id);

ALTER TABLE categorias ADD CONSTRAINT pk_categorias PRIMARY KEY (id);

ALTER TABLE carritos ADD CONSTRAINT pk_carritos PRIMARY KEY (id);

ALTER TABLE pedidos_detalles ADD CONSTRAINT pk_pedidos_detalles PRIMARY KEY (id);

ALTER TABLE categorias_marcas ADD CONSTRAINT pk_categorias_marcas PRIMARY KEY (id);

ALTER TABLE carritos_detalles ADD CONSTRAINT pk_carritos_detalles PRIMARY KEY (id);

ALTER TABLE carritos ADD CONSTRAINT fk_carritos_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE;

ALTER TABLE carritos_detalles ADD CONSTRAINT fk_carritos_detalles_carritos_carrito_id FOREIGN KEY (carrito_id) REFERENCES carritos (id) ON DELETE CASCADE;

ALTER TABLE carritos_detalles ADD CONSTRAINT fk_carritos_detalles_productos_producto_id FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE CASCADE;

ALTER TABLE categorias_marcas ADD CONSTRAINT fk_categorias_marcas_categorias_categoria_id FOREIGN KEY (categoria_id) REFERENCES categorias (id) ON DELETE CASCADE;

ALTER TABLE categorias_marcas ADD CONSTRAINT fk_categorias_marcas_marcas_marca_id FOREIGN KEY (marca_id) REFERENCES marcas (id) ON DELETE CASCADE;

ALTER TABLE marcas ADD CONSTRAINT fk_marcas_paises_pais_id FOREIGN KEY (pais_id) REFERENCES paises (id) ON DELETE RESTRICT;

ALTER TABLE pedidos ADD CONSTRAINT fk_pedidos_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES usuarios (id) ON DELETE CASCADE;

ALTER TABLE pedidos_detalles ADD CONSTRAINT fk_pedidos_detalles_pedidos_pedido_id FOREIGN KEY (pedido_id) REFERENCES pedidos (id) ON DELETE CASCADE;

ALTER TABLE pedidos_detalles ADD CONSTRAINT fk_pedidos_detalles_productos_producto_id FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE CASCADE;

ALTER TABLE productos ADD CONSTRAINT fk_productos_categorias_categoria_id FOREIGN KEY (categoria_id) REFERENCES categorias (id) ON DELETE CASCADE;

ALTER TABLE productos ADD CONSTRAINT fk_productos_marcas_marca_id FOREIGN KEY (marca_id) REFERENCES marcas (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260407144002_UseSnakeCaseNaming', '9.0.9');


SELECT setval(
  pg_get_serial_sequence('carritos', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM carritos), 0), 1),
  true
);
SELECT setval(
  pg_get_serial_sequence('carritos_detalles', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM carritos_detalles), 0), 1),
  true
);


INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260408004116_FixCarritosIdSequences', '9.0.9');


SELECT setval(pg_get_serial_sequence('pedidos', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM pedidos), 0), 1), true);
SELECT setval(pg_get_serial_sequence('pedidos_detalles', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM pedidos_detalles), 0), 1), true);
SELECT setval(pg_get_serial_sequence('productos', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM productos), 0), 1), true);
SELECT setval(pg_get_serial_sequence('categorias', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM categorias), 0), 1), true);
SELECT setval(pg_get_serial_sequence('marcas', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM marcas), 0), 1), true);
SELECT setval(pg_get_serial_sequence('paises', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM paises), 0), 1), true);
SELECT setval(pg_get_serial_sequence('categorias_marcas', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM categorias_marcas), 0), 1), true);
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM usuarios), 0), 1), true);


INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260408004907_FixPedidosYTablasIdSequences', '9.0.9');

ALTER TABLE usuarios RENAME COLUMN password TO "Password";

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260410191933_SyncPendingModel', '9.0.9');

ALTER TABLE productos ADD color text;

ALTER TABLE productos ADD material_funda text;

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260414193025_ProductoMaterialFundaColor', '9.0.9');

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260415193852_ProductoMaterialFundaColor2', '9.0.9');

INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260415201822_CarritoDetalleColor', '9.0.9');


DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_attribute a
    INNER JOIN pg_class c ON c.oid = a.attrelid
    INNER JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'usuarios'
      AND a.attname = 'Password' AND a.attnum > 0 AND NOT a.attisdropped
  ) THEN
    EXECUTE 'ALTER TABLE usuarios RENAME COLUMN "Password" TO password';
  END IF;
END $$;


INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
VALUES ('20260416120000_AlignUsuarioPasswordColumnSnakeCase', '9.0.9');

COMMIT;

